### ISSUE TITLE
Default page & instructions

### ISSUE THREAD

**Issue by JamborJan** [ndarilek/hugo-sandstorm#2]
Hey @ndarilek,

While trying Hugo within Snadstorm I realized there is no default webside. I usually prefer when Sandstorm ports work out of the box which would mean a simple default page including examples for the maior features e.g. a easy menu, graphics and main elements. Maybe also with some insructions like `to change the menue edit file xyz` etc. Do you think that would be possible?

Thanks & cheers
JJ

**Comment by ndarilek** [comment]
I go back and forth on this. All the points you mention are valid, but 
`hugo new` also gives you a blank site with no default theme. By 
contrast, other static site generators give you a basic default that you 
can tweak.

Another challenge is that there are lots of themes at 
https://themes.gohugo.io, but the best way to use them with Sandstorm I 
think is to use Git subtrees. So if I set up a default theme in a way 
that you'd probably want to continue with, I'd add the subtree to the 
repo. If that *isn't* the theme you want, you're then stuck *undoing* 
the subtree add, which is a bit of ugly mucking around with your 
repository history.

I'll leave this open since I'd be interested in others' thoughts. As a 
compromise, I may add instructions into the start page on how to add a 
theme from the themes site as a subtree, and how to create a starter 
index page. I really wish Hugo shipped a default theme, because having 
to pick one from the themes site is kind of overwhelming.

**Comment by JamborJan** [comment]
I like when I can check out an app and it works with easy steps. Right now when I try to setup a Hugo instance I cannot check a default page. When clicking the link mentioned on the start page I get a 404 and I have to read in detail how to use Hugo in the documents. It would be really cool if at least the basic first steps are explained and a default page is working out of the box. I'll try to work something out and send a PR.

**Comment by ndarilek** [comment]
Fair enough. Here's what I've done:

I've added instructions for how to publish an existing Hugo site to the 
grain. These instructions advise using `git push -f` to override an 
existing default site, which will presumably be added.

If you can send me a PR for a minimal Hugo site which includes:
  * a content/index.md with some basic "getting started" instructions, 
with a pointer to Hugo's docs and to themes.gohugo.io
  * A minimally styled template page that renders the index.md, but not 
a full theme

I'll add those to the Git repository. At least then it won't 404, and I 
won't have to bring in a full theme, or make assumptions about whether 
the user is building a blog, portfolio site, etc.

Thanks.

**Comment by JamborJan** [comment]
Did I get right, that you must run `hugo server` to get a page build? 

I would expect that I can simply push my page build with a couple of md-files theme etc to the git repo and the stuff is running. If there is any build process which must be triggered it should be some kind of "rebuild static content" button in the app like we have it in the wordpress app.

Until now I'm not even able to create a simple hello world webpage. No matter what I do I always get `404 not found: /index.html` in Sandstorm. To be fair I am not familiar with Hugo and reading the manuals don't helps as there are always a bunch of `hugo` commands explained.

Again my expectation would be: create a new grain in Sandstorm, git clone the repo, edit stuff and add things, git push, maybe a rebuild content button, done. No need to install Hugo locally.

**Comment by ndarilek** [comment]
There is no need to install Hugo locally to use this grain, nor is there 
a manual rebuild step.

Due to Hugo's nature, though, you *probably* want to run it locally, 
test changes via its live reload feature, then push them when you're 
ready to publish. It's kind of the nature of these tools that you're 
expected to do your previewing and such locally, then publish your 
changes remotely when the local build looks good. The admin interface, 
while present, is mainly meant for making quick changes on the go. You 
might, for instance, push a draft post from one location, then edit it 
in the admin interface elsewhere. Draft posts aren't published by 
default, so this gives you the best of both worlds--web-based editor and 
command line workflow.

The new changes I just pushed will give you a minimal, unstyled site 
with a few pointers on where to get started. Feel free to contribute PRs 
to make it look nice if you like, but I don't want to bring in a full 
theme, CSS framework, or anything huge.

Thanks for the feedback.
