### ISSUE TITLE
Themes do not appear to work

### ISSUE THREAD

**Issue by ocdtrekkie** [ndarilek/hugo-sandstorm#6]
IRC user @georgeowell (guessing same user ID perhaps?) has confirmed this issue. Neither of us were able to get themes working in Hugo, even though we did not get error messages about it.

```
<georgeowell> Has anyone had issues with the Hugo app? Some of themes arn't being cooperative.
<georgeowell> in the sense that i can't get it to work at all
<ocdtr_web> georgeowell: I was also unable to get themes to work on my Hugo test, but assumed I was just doing it wrong!
<ocdtr_web> nolan_d is the Hugo app maintainer, and I know he generally recommends setting up your Hugo site and stuff on a normal/local Hugo install, and then pushing the result to the Sandstorm version, but I haven't tried it myself.
<georgeowell> it might be good to put that in the documentation
<georgeowell> I was wrestling with it for ages and couldnt get any of the themes to work
<ocdtr_web> It would probably be a good idea since two of us have experienced issues getting themes to work, that we (and nolan_d) should figure out why they don't work and fix it. :D
<georgeowell> I must say I'm scratching my head. It's just not compiling properly with no errors I can find.
<georgeowell> I did manage to get it to "build" some of the files but with none of the styling
<ocdtr_web> Same experience I had.
```

**Comment by ndarilek** [comment]
Interesting, how are you loading the theme into your repository?

I'm running https://www.thewordnerd.info via this app and I assume the 
theme works there.

Do you see anything strange in the output when pushing?

**Comment by georgeowell** [comment]
I tried both doing a git clone and a git submodule for maybe 3 or 4 random themes. No errors when pushing or server side, though I've not used Hugo before so I might be missing something. Basically nothing happens and the default instructions site is still in place.

**Comment by ndarilek** [comment]
The submodule won't work because Sandstorm can't connect externally 
during the build procedure to retrieve the theme repo. You'll either 
need to:

  * Commit theme files directly into your repository as if they were 
your own content.

  * Add the theme repo as a git subtree. I think this pulls in all the 
commits for a repo, but checks the content out at a subdirectory in your 
current repo. So IOW, a theme's commits are all pulled in and checked 
out at themes/twentyfourteen or wherever.


I do this with a couple sites and it works. Finding tutorials for it is 
a bit difficult, though. Bitbucket had a good one IIRC but even some of 
the commands didn't work as advertised. Whenever I have to add a theme 
subtree I just sort of hold my nose, get it done, then move on. Really 
wish Sandstorm supported some sort of less restrictive external 
connection model so I could just add a submodule and get on with my day.

**Comment by ocdtrekkie** [comment]
I think I committed the theme files directly into my repository, and it still didn't take.

**Comment by ndarilek** [comment]
Wild, and they work when you build locally? I know of no reason they 
shouldn't work.

**Comment by ocdtrekkie** [comment]
Building locally is something I meant to try but haven't done.

**Comment by ocdtrekkie** [comment]
I'm going to close this because it's super old, and if I try Hugo again and have issues, I'll file it on the new repo.
